export const ACTION_LABELS: Record<string, string> = {
  seed: 'Initialisation',
  login: 'Connexion',
  task_created: 'Tâche créée',
  task_updated: 'Tâche modifiée',
  task_deleted: 'Tâche supprimée',
  task_submitted: 'Tâche signalée',
  submission_approved: 'Tâche validée',
  submission_rejected: 'Tâche refusée',
  penalty_applied: 'Pénalité appliquée',
  penalty_cancelled: 'Pénalité annulée',
  balance_adjusted: 'Ajustement de solde',
  balance_reset: 'Solde réinitialisé',
  child_updated: 'Profil enfant modifié',
  secret_changed: 'Code modifié',
  settings_updated: 'Réglages modifiés',
  message_sent: 'Message envoyé',
  avatar_changed: 'Avatar modifié',
  submission_approval_reverted: 'Validation annulée',
  penalty_deleted: 'Pénalité supprimée',
  penalty_edited: 'Pénalité modifiée',
  reward_earned: 'Récompense gagnée',
  penalty_rule_created: 'Règle de pénalité créée',
  penalty_rule_updated: 'Règle de pénalité modifiée',
  penalty_rule_deleted: 'Règle de pénalité supprimée',
  penalty_rule_auto_applied: 'Pénalité automatique (règle)',
  inactivity_penalty_applied: "Pénalité d'inactivité",
  shop_item_created: 'Lot ajouté à la boutique',
  shop_item_deleted: 'Lot retiré de la boutique',
  wish_submitted: 'Vœu proposé',
  wish_approved: 'Vœu accepté',
  wish_rejected: 'Vœu refusé',
  redemption_requested: 'Échange demandé',
  redemption_fulfilled: 'Échange remis',
  redemption_cancelled: 'Échange annulé',
  points_converted: 'Points convertis en argent',
  user_created: 'Profil créé',
  streak_def_created: 'Série créée',
  streak_def_updated: 'Série modifiée',
  streak_def_deleted: 'Série supprimée',
  badge_def_created: 'Badge créé',
  badge_def_updated: 'Badge modifié',
  badge_def_deleted: 'Badge supprimé',
  rank_def_created: 'Rang créé',
  rank_def_updated: 'Rang modifié',
  rank_def_deleted: 'Rang supprimé',
  savings_goal_created: "Objectif d'épargne créé",
  savings_goal_deleted: "Objectif d'épargne supprimé",
  shop_item_updated: 'Lot de la boutique modifié',
  submission_deleted: 'Validation supprimée définitivement',
  custom_notification_sent: 'Notification envoyée',
  daily_reminder_sent: 'Rappel quotidien envoyé',
}

export function actionLabel(action: string): string {
  return ACTION_LABELS[action] ?? action
}
